local SL = lord.require_intllib()

--mobs:register_egg("lottmobs:dragon_great", "Boss Dragon", "mobs_dragon_egg.png", 1)
--mobs:register_egg("lottmobs:dragon_great_tame", "Great Dragon", "default_lava_source_animated.png", 1)

mobs:register_egg("lottmobs:elf_archer", "Elf archer", "default_leaves_simple.png", 1)

mobs:register_egg("lottmobs:troll", "Troll", "default_leaves_simple.png", 1)
mobs:register_egg("lottmobs:dead_men", "Dead Man", "default_mineral_coal.png", 1)
mobs:register_egg("lottmobs:balrog", "Barlog", "default_mineral_copper.png", 1)
mobs:register_egg("lottmobs:warg", "Warg", "default_pine_needles.png", 1)
mobs:register_egg("lottmobs:witch_king", "Witch King", "default_mineral_iron.png", 1)
mobs:register_egg("lottmobs:nazgul", "Nazgul", "default_scorched_stuff.png", 1)
mobs:register_egg("lottmobs:half_troll", "Half Troll", "default_tnt_bottom.png", 1)
mobs:register_egg("lottmobs:battle_troll", "Battle Troll", "building_blocks_cast_iron.png", 1)
mobs:register_egg("lottmobs:uruk_hai", "Uruk Hai", "building_blocks_grate.png", 1)
mobs:register_egg("lottmobs:raiding_orc", "Raiding Orc", "building_blocks_Roofing.png", 1)
mobs:register_egg("lottmobs:orc", "Orc", "building_blocks_tar.png", 1)
mobs:register_egg("lottmobs:orc_archer", "Orc archer", "building_blocks_tar.png", 1)
mobs:register_egg("lottmobs:orc_crossbowman", "Orc crossbowman", "building_blocks_tar.png", 1)
mobs:register_egg("lottmobs:raiding_orc", "Raiding Orc", "homedecor_curtain.png", 1)
