local SL = minetest.get_mod_translator()

return {
	get_recipes = function(source)
		return {{
			{source},
			{'group:stick'},
		}}
	end,
	wood        = {
		description         = SL("Wooden Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = 2.25, [3] = 1.75 }, uses = 2, maxlevel = 1 },
		damage_groups       = { fleshy = .65 },
		full_punch_interval = .25,
		groups              = { wooden = 1 },
	},
	stone       = {
		description         = SL("Stone Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = 1.35, [3] = 0.85 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = .70 },
		full_punch_interval = 0.25,
	},
	steel       = {
		description         = SL("Steel Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = 1.00, [3] = 0.50 }, uses = 10, maxlevel = 1 },
		damage_groups       = { fleshy = 1.5 },
		full_punch_interval = 0.5,
		groups              = { steel_item = 1 },
	},
	bronze      = {
		description         = SL("Bronze Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = 1.00, [3] = 0.50 }, uses = 15, maxlevel = 1 },
		damage_groups       = { fleshy = 2.2 },
		full_punch_interval = 0.5,
		groups              = { bronze_item = 1 },
	},
	copper      = {
		description         = SL("Copper Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = 1.25, [3] = 0.75 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = 1.8 },
		full_punch_interval = 0.45,
		groups              = { copper_item = 1 },
	},
	tin         = {
		description         = SL("Tin Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = 1.25, [3] = 0.75 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = 1.2 },
		full_punch_interval = 0.4,
		groups              = { tin_item = 1 },
	},
	silver      = {
		description         = SL("Silver Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = .80, [3] = 0.40 }, uses = 10, maxlevel = 1 },
		damage_groups       = { fleshy = 3.5625 },
		full_punch_interval = 0.75,
		groups              = { silver_item = 1 },
	},
	gold        = {
		description         = SL("Gold Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = .80, [3] = 0.40 }, uses = 15, maxlevel = 1 },
		damage_groups       = { fleshy = 3.84 },
		full_punch_interval = .8,
		groups              = { gold_item = 1 },
	},
	galvorn     = {
		description         = SL("Galvorn Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = .90, [3] = 0.45 }, uses = 20, maxlevel = 1 },
		damage_groups       = { fleshy = 6.0 },
		full_punch_interval = 1.0,
		groups              = { forbidden = 1, galvorn_item = 1 },
	},
	mithril     = {
		description         = SL("Mithril Dagger"),
		range               = 2,
		max_drop_level      = 0,
		snappy              = { times = { [2] = .75, [3] = 0.35 }, uses = 25, maxlevel = 2 },
		damage_groups       = { fleshy = 2.0 },
		full_punch_interval = .25,
		groups              = { mithril_item = 1 },
	}
}
