local SL = minetest.get_translator("tools")

return {
	get_recipes = function(source)
		return {{
			{'', source, ''},
			{source, 'group:stick', source},
			{'', 'group:stick', ''},
		}}
	end,
	wood        = {
		description           = SL("Wooden Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 3.70, [2] = 2.70, [3] = 1.70 }, uses = 3, maxlevel = 1 },
		damage_groups         = { fleshy = 4.5 },
		full_punch_interval   = 1.5,
		groups                = { wooden = 1 },
	},
	stone       = {
		description           = SL("Stone Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.75, [2] = 1.75, [3] = 0.75 }, uses = 5, maxlevel = 1 },
		damage_groups         = { fleshy = 5.5 },
		full_punch_interval   = 1.55,
	},
	steel       = {
		description           = SL("Steel Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.40, [2] = 1.40, [3] = 0.40 }, uses = 15, maxlevel = 1 },
		damage_groups         = { fleshy = 6.8 },
		full_punch_interval   = 1.70,
		groups                = { steel_item = 1 },
	},
	bronze      = {
		description           = SL("Bronze Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.40, [2] = 1.40, [3] = 0.40 }, uses = 20, maxlevel = 1 },
		damage_groups         = { fleshy = 7.92 },
		full_punch_interval   = 1.80,
		groups                = { bronze_item = 1 },
	},
	copper      = {
		description           = SL("Copper Spear"),
		wield_image_transform = "^[transformFX",
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.70, [2] = 1.70, [3] = 0.70 }, uses = 5, maxlevel = 1 },
		damage_groups         = { fleshy = 7.7 },
		full_punch_interval   = 1.79,
		groups                = { copper_item = 1 },
	},
	tin         = {
		description           = SL("Tin Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.70, [2] = 1.70, [3] = 0.70 }, uses = 5, maxlevel = 1 },
		damage_groups         = { fleshy = 7.7 },
		full_punch_interval   = 1.79,
		groups                = { tin_item = 1 },
	},
	silver      = {
		description           = SL("Silver Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.2, [2] = 1.2, [3] = 0.20 }, uses = 15, maxlevel = 1 },
		damage_groups         = { fleshy = 8.65 },
		full_punch_interval   = 1.8,
		groups                = { silver_item = 1 },
	},
	gold        = {
		description           = SL("Gold Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.2, [2] = 1.2, [3] = 0.20 }, uses = 20, maxlevel = 1 },
		damage_groups         = { fleshy = 9.12 },
		full_punch_interval   = 1.9,
		groups                = { gold_item = 1 },
	},
	galvorn     = {
		description           = SL("Galvorn Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.3, [2] = 1.3, [3] = 0.30 }, uses = 25, maxlevel = 1 },
		damage_groups         = { fleshy = 12 },
		full_punch_interval   = 2.00,
		groups                = { forbidden = 1, galvorn_item = 1 },
	},
	mithril     = {
		description           = SL("Mithril Spear"),
		wield_image_transform = "^[transformFX",
		range                 = 7,
		max_drop_level        = 1,
		snappy                = { times = { [1] = 2.00, [2] = 1.00, [3] = 0.20 }, uses = 30, maxlevel = 2 },
		damage_groups         = { fleshy = 12 },
		full_punch_interval   = 1.50,
		groups                = { mithril_item = 1 },
	}
}
