local SL = minetest.get_mod_translator()

return {
	get_recipes = function(source)
		return {{
			{source, source, source},
			{source, 'group:stick', source},
			{'', 'group:stick', ''},
		}}
	end,
	wood        = {
		description         = SL("Wooden Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 3.40, [2] = 2.40, [3] = 1.30 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = 15 },
		full_punch_interval = 2,
		groups              = { wooden = 1 },
	},
	stone       = {
		description         = SL("Stone Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.85, [2] = 1.85, [3] = 1.10 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = 18.4 },
		full_punch_interval = 2.3,
	},
	steel       = {
		description         = SL("Steel Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.75, [2] = 1.45, [3] = 0.60 }, uses = 25, maxlevel = 2 },
		damage_groups       = { fleshy = 20 },
		full_punch_interval = 2.5,
		groups              = { steel_item = 1 },
	},
	bronze      = {
		description         = SL("Bronze Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.75, [2] = 1.45, [3] = 0.60 }, uses = 30, maxlevel = 2 },
		damage_groups       = { fleshy = 26.10 },
		full_punch_interval = 2.90,
		groups              = { bronze_item = 1 },
	},
	copper      = {
		description         = SL("Copper Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 3, [2] = 1.80, [3] = 1.00 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = 21.81 },
		full_punch_interval = 2.45,
		groups              = { copper_item = 1 },
	},
	tin         = {
		description         = SL("Tin Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 3, [2] = 1.80, [3] = 1.00 }, uses = 5, maxlevel = 1 },
		damage_groups       = { fleshy = 20.4 },
		full_punch_interval = 2.4,
		groups              = { tin_item = 1 },
	},
	silver      = {
		description         = SL("Silver Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.60, [2] = 1.40, [3] = 0.50 }, uses = 20, maxlevel = 2 },
		damage_groups       = { fleshy = 29 },
		full_punch_interval = 2.9,
		groups              = { silver_item = 1 },
	},
	gold        = {
		description         = SL("Gold Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.60, [2] = 1.40, [3] = 0.50 }, uses = 30, maxlevel = 2 },
		damage_groups       = { fleshy = 33 },
		full_punch_interval = 3,
		groups              = { gold_item = 1 },
	},
	galvorn     = {
		description         = SL("Galvorn Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.50, [2] = 1.30, [3] = 0.45 }, uses = 35, maxlevel = 2 },
		damage_groups       = { fleshy = 36 },
		full_punch_interval = 3,
		groups              = { forbidden = 1, galvorn_item = 1 },
	},
	mithril     = {
		description         = SL("Mithril Warhammer"),
		range               = 3,
		max_drop_level      = 1,
		snappy              = { times = { [1] = 2.60, [2] = 1.40, [3] = 0.50 }, uses = 40, maxlevel = 3 },
		damage_groups       = { fleshy = 25 },
		full_punch_interval = 2,
		groups              = { mithril_item = 1 },
	}
}
