language: generic
sudo: false
addons:
  apt:
    packages:
      - luarocks
before_install:
  - luarocks install --local luacheck
script:
  - $HOME/.luarocks/bin/luacheck .
notifications:
  email: false
