title = L.O.R.D. Game
description = MMO survival sanbox inspired by the legendarium of J. Tolkien ("The Lord of the Rings", "The Hobbit", ...)
allowed_mapgens = v7, flat, singlenode
default_mapgen = v7
