local SL = lord.require_intllib()

tools.spear = {
	get_recipes = function(source)
		return {{
			{'', source, ''},
			{source, 'group:stick', source},
			{'', 'group:stick', ''},
		}}
	end,
	wood = {
		description = SL("Training Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 2,
		max_drop_level=1,
		snappy={times={[1]=3.70, [2]=2.70, [3]=1.70}, uses=3, maxlevel=1},
		damage_groups = {fleshy=.75},
		groups = {wooden = 1},
	},
	stone = {
		description = SL("Stone Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 1.50,
		max_drop_level=1,
		snappy={times={[1]=2.75, [2]=1.75, [3]=0.75}, uses=5, maxlevel=1},
		damage_groups = {fleshy=2},
	},
	steel = {
		description = SL("Steel Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 1.20,
		max_drop_level=1,
		snappy={times={[1]=2.40, [2]=1.40, [3]=0.40}, uses=15, maxlevel=1},
		damage_groups = {fleshy=5},
		groups = {steel_item = 1},
	},
	bronze = {
		description = SL("Bronze Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 1.10,
		max_drop_level=1,
		snappy={times={[1]=2.40, [2]=1.40, [3]=0.40}, uses=20, maxlevel=1},
		damage_groups = {fleshy=5.5},
		groups = {bronze_item = 1},
	},
	copper = {
		description = SL("Copper Spear"),
		wield_image_transform = "^[transformFX",
		full_punch_interval = 1.30,
		max_drop_level=1,
		snappy={times={[1]=2.70, [2]=1.70, [3]=0.70}, uses=5, maxlevel=1},
		damage_groups = {fleshy=4},
		groups = {copper_item = 1},
	},
	tin = {
		description = SL("Tin Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 1.30,
		max_drop_level=1,
		snappy={times={[1]=2.70, [2]=1.70, [3]=0.70}, uses=5, maxlevel=1},
		damage_groups = {fleshy=4},
		groups = {tin_item = 1},
	},
	silver = {
		description = SL("Silver Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 1,
		max_drop_level=1,
		snappy={times={[1]=2.2, [2]=1.2, [3]=0.20}, uses=15, maxlevel=1},
		damage_groups = {fleshy=6},
		groups = {silver_item = 1},
	},
	gold = {
		description = SL("Gold Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 0.75,
		max_drop_level=1,
		snappy={times={[1]=2.2, [2]=1.2, [3]=0.20}, uses=20, maxlevel=1},
		damage_groups = {fleshy=6},
		groups = {gold_item = 1},
	},
	galvorn = {
		description = SL("Galvorn Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 0.50,
		max_drop_level=1,
		snappy={times={[1]=2.3, [2]=1.3, [3]=0.30}, uses=25, maxlevel=1},
		damage_groups = {fleshy=7},
		groups = {forbidden=1, galvorn_item=1},
	},
	mithril = {
		description = SL("Mithril Spear"),
		wield_image_transform = "^[transformFX",
		range = 7,
		full_punch_interval = 0.25,
		max_drop_level=1,
		snappy={times={[1]=2.00, [2]=1.00, [3]=0.20}, uses=30, maxlevel=2},
		damage_groups = {fleshy=8},
		groups = {mithril_item = 1},
	}
}
