
-- /!\ poisoned arrows are removed

-- Temporary aliases.
-- TODO: remove this ones & uncomment in mods/lord/Tools/lord_potions/legacy.lua:48 (#1736)
minetest.register_alias('lottpotion:athelasbrew_power1_arrow', 'lottpotion:athelasbrew_power1')
minetest.register_alias('lottpotion:athelasbrew_power2_arrow', 'lottpotion:athelasbrew_power2')
minetest.register_alias('lottpotion:athelasbrew_power3_arrow', 'lottpotion:athelasbrew_power3')
minetest.register_alias('lottpotion:athelasbrew_corruption1_arrow', 'lottpotion:athelasbrew_corruption1')
minetest.register_alias('lottpotion:athelasbrew_corruption2_arrow', 'lottpotion:athelasbrew_corruption2')
minetest.register_alias('lottpotion:athelasbrew_corruption3_arrow', 'lottpotion:athelasbrew_corruption3')
minetest.register_alias('lottpotion:limpe_power1_arrow', 'lottpotion:limpe_power1')
minetest.register_alias('lottpotion:limpe_power2_arrow', 'lottpotion:limpe_power2')
minetest.register_alias('lottpotion:limpe_power3_arrow', 'lottpotion:limpe_power3')
minetest.register_alias('lottpotion:limpe_corruption1_arrow', 'lottpotion:limpe_corruption1')
minetest.register_alias('lottpotion:limpe_corruption2_arrow', 'lottpotion:limpe_corruption2')
minetest.register_alias('lottpotion:limpe_corruption3_arrow', 'lottpotion:limpe_corruption3')
minetest.register_alias('lottpotion:miruvor_power1_arrow', 'lottpotion:miruvor_power1')
minetest.register_alias('lottpotion:miruvor_power2_arrow', 'lottpotion:miruvor_power2')
minetest.register_alias('lottpotion:miruvor_power3_arrow', 'lottpotion:miruvor_power3')
minetest.register_alias('lottpotion:miruvor_corruption1_arrow', 'lottpotion:miruvor_corruption1')
minetest.register_alias('lottpotion:miruvor_corruption2_arrow', 'lottpotion:miruvor_corruption2')
minetest.register_alias('lottpotion:miruvor_corruption3_arrow', 'lottpotion:miruvor_corruption3')
minetest.register_alias('lottpotion:spiderpoison_power1_arrow', 'lottpotion:spiderpoison_power1')
minetest.register_alias('lottpotion:spiderpoison_power2_arrow', 'lottpotion:spiderpoison_power2')
minetest.register_alias('lottpotion:spiderpoison_power3_arrow', 'lottpotion:spiderpoison_power3')
minetest.register_alias('lottpotion:spiderpoison_corruption1_arrow', 'lottpotion:spiderpoison_corruption1')
minetest.register_alias('lottpotion:spiderpoison_corruption2_arrow', 'lottpotion:spiderpoison_corruption2')
minetest.register_alias('lottpotion:spiderpoison_corruption3_arrow', 'lottpotion:spiderpoison_corruption3')
minetest.register_alias('lottpotion:orcdraught_power1_arrow', 'lottpotion:orcdraught_power1')
minetest.register_alias('lottpotion:orcdraught_power2_arrow', 'lottpotion:orcdraught_power2')
minetest.register_alias('lottpotion:orcdraught_power3_arrow', 'lottpotion:orcdraught_power3')
minetest.register_alias('lottpotion:orcdraught_corruption1_arrow', 'lottpotion:orcdraught_corruption1')
minetest.register_alias('lottpotion:orcdraught_corruption2_arrow', 'lottpotion:orcdraught_corruption2')
minetest.register_alias('lottpotion:orcdraught_corruption3_arrow', 'lottpotion:orcdraught_corruption3')
minetest.register_alias('lottpotion:entdraught_power1_arrow', 'lottpotion:entdraught_power1')
minetest.register_alias('lottpotion:entdraught_power2_arrow', 'lottpotion:entdraught_power2')
minetest.register_alias('lottpotion:entdraught_power3_arrow', 'lottpotion:entdraught_power3')
minetest.register_alias('lottpotion:entdraught_corruption1_arrow', 'lottpotion:entdraught_corruption1')
minetest.register_alias('lottpotion:entdraught_corruption2_arrow', 'lottpotion:entdraught_corruption2')
minetest.register_alias('lottpotion:entdraught_corruption3_arrow', 'lottpotion:entdraught_corruption3')
