name = lord_smelter
depends = voxrame_builtin_ext, default, voxrame_fuel_device
optional_depends = lord_overwrites_mtg_default, lord_default, lottores, lottother, lord_overwrites_mtg_carts, vessels, keys
