dofile(minetest.get_modpath("npc").."/npc.lua")
dofile(minetest.get_modpath("npc").."/dummy_mob.lua")
dofile(minetest.get_modpath("npc").."/info_mob.lua")
dofile(minetest.get_modpath("npc").."/changer_mob.lua")
dofile(minetest.get_modpath("npc").."/e_deputy_mob.lua")
