version: '3.7'

services:
 matterbridge:
   image: 42wim/matterbridge:1.25.2
   volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
   ports:
    - 4242:4242

 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.6.0
  entrypoint: minetestserver --config /minetest.conf
  user: root
  volumes:
    - "../:/root/.minetest/worlds/world/worldmods/beerchat/"
    - "world_data:/root/.minetest/worlds/world"
    - "./world.mt:/root/.minetest/worlds/world/world.mt"
    - "./minetest.conf:/minetest.conf"
  ports:
    - "30000:30000/udp"

volumes:
  world_data: {}