[irc]
[irc.Libera]
Server="irc.libera.chat:6667"
Nick="BeerchatTestBot"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
ColorNicks=true
ShowJoinPart=true

[discord]
[discord.Discord]
Token="<omitted>"
Server="839951944515715084"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
ShowJoinPart=true
UseUserName=true
AllowMention=["users"]

[api.minetest]
BindAddress="0.0.0.0:4242"
Token="mytoken"
Buffer=1000
RemoteNickFormat="[{BRIDGE}] {NICK}"
ShowJoinPart=true

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#beerchat"
[[gateway.inout]]
account = "discord.Discord"
channel="matterbridge"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="main2"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#beerchat2"
[[gateway.inout]]
account="api.minetest"
channel="api"