local function register_doors_aliases()
	core.register_alias( "lottblocks:door_alder",             "lord_wooden_stuff:door_alder"             )
	core.register_alias( "lottblocks:door_alder_a",           "lord_wooden_stuff:door_alder_a"           )
	core.register_alias( "lottblocks:door_alder_b",           "lord_wooden_stuff:door_alder_b"           )
	core.register_alias( "lottblocks:door_alder_c",           "lord_wooden_stuff:door_alder_c"           )
	core.register_alias( "lottblocks:door_alder_d",           "lord_wooden_stuff:door_alder_d"           )
	core.register_alias( "lottblocks:door_alder_lock",        "lord_wooden_stuff:door_alder_lock"        )
	core.register_alias( "lottblocks:door_alder_lock_a",      "lord_wooden_stuff:door_alder_lock_a"      )
	core.register_alias( "lottblocks:door_alder_lock_b",      "lord_wooden_stuff:door_alder_lock_b"      )
	core.register_alias( "lottblocks:door_alder_lock_c",      "lord_wooden_stuff:door_alder_lock_c"      )
	core.register_alias( "lottblocks:door_alder_lock_d",      "lord_wooden_stuff:door_alder_lock_d"      )
	core.register_alias( "lottblocks:door_birch",             "lord_wooden_stuff:door_birch"             )
	core.register_alias( "lottblocks:door_birch_a",           "lord_wooden_stuff:door_birch_a"           )
	core.register_alias( "lottblocks:door_birch_b",           "lord_wooden_stuff:door_birch_b"           )
	core.register_alias( "lottblocks:door_birch_c",           "lord_wooden_stuff:door_birch_c"           )
	core.register_alias( "lottblocks:door_birch_d",           "lord_wooden_stuff:door_birch_d"           )
	core.register_alias( "lottblocks:door_birch_lock",        "lord_wooden_stuff:door_birch_lock"        )
	core.register_alias( "lottblocks:door_birch_lock_a",      "lord_wooden_stuff:door_birch_lock_a"      )
	core.register_alias( "lottblocks:door_birch_lock_b",      "lord_wooden_stuff:door_birch_lock_b"      )
	core.register_alias( "lottblocks:door_birch_lock_c",      "lord_wooden_stuff:door_birch_lock_c"      )
	core.register_alias( "lottblocks:door_birch_lock_d",      "lord_wooden_stuff:door_birch_lock_d"      )
	core.register_alias( "lottblocks:door_hardwood",          "lord_wooden_stuff:door_hardwood"          )
	core.register_alias( "lottblocks:door_hardwood_a",        "lord_wooden_stuff:door_hardwood_a"        )
	core.register_alias( "lottblocks:door_hardwood_b",        "lord_wooden_stuff:door_hardwood_b"        )
	core.register_alias( "lottblocks:door_hardwood_c",        "lord_wooden_stuff:door_hardwood_c"        )
	core.register_alias( "lottblocks:door_hardwood_d",        "lord_wooden_stuff:door_hardwood_d"        )
	core.register_alias( "lottblocks:door_hardwood_lock",     "lord_wooden_stuff:door_hardwood_lock"     )
	core.register_alias( "lottblocks:door_hardwood_lock_a",   "lord_wooden_stuff:door_hardwood_lock_a"   )
	core.register_alias( "lottblocks:door_hardwood_lock_b",   "lord_wooden_stuff:door_hardwood_lock_b"   )
	core.register_alias( "lottblocks:door_hardwood_lock_c",   "lord_wooden_stuff:door_hardwood_lock_c"   )
	core.register_alias( "lottblocks:door_hardwood_lock_d",   "lord_wooden_stuff:door_hardwood_lock_d"   )
	core.register_alias( "lottblocks:door_junglewood",        "lord_wooden_stuff:door_junglewood"        )
	core.register_alias( "lottblocks:door_junglewood_a",      "lord_wooden_stuff:door_junglewood_a"      )
	core.register_alias( "lottblocks:door_junglewood_b",      "lord_wooden_stuff:door_junglewood_b"      )
	core.register_alias( "lottblocks:door_junglewood_c",      "lord_wooden_stuff:door_junglewood_c"      )
	core.register_alias( "lottblocks:door_junglewood_d",      "lord_wooden_stuff:door_junglewood_d"      )
	core.register_alias( "lottblocks:door_junglewood_lock",   "lord_wooden_stuff:door_junglewood_lock"   )
	core.register_alias( "lottblocks:door_junglewood_lock_a", "lord_wooden_stuff:door_junglewood_lock_a" )
	core.register_alias( "lottblocks:door_junglewood_lock_b", "lord_wooden_stuff:door_junglewood_lock_b" )
	core.register_alias( "lottblocks:door_junglewood_lock_c", "lord_wooden_stuff:door_junglewood_lock_c" )
	core.register_alias( "lottblocks:door_junglewood_lock_d", "lord_wooden_stuff:door_junglewood_lock_d" )
	core.register_alias( "lottblocks:door_lebethron",         "lord_wooden_stuff:door_lebethron"         )
	core.register_alias( "lottblocks:door_lebethron_a",       "lord_wooden_stuff:door_lebethron_a"       )
	core.register_alias( "lottblocks:door_lebethron_b",       "lord_wooden_stuff:door_lebethron_b"       )
	core.register_alias( "lottblocks:door_lebethron_c",       "lord_wooden_stuff:door_lebethron_c"       )
	core.register_alias( "lottblocks:door_lebethron_d",       "lord_wooden_stuff:door_lebethron_d"       )
	core.register_alias( "lottblocks:door_lebethron_lock",    "lord_wooden_stuff:door_lebethron_lock"    )
	core.register_alias( "lottblocks:door_lebethron_lock_a",  "lord_wooden_stuff:door_lebethron_lock_a"  )
	core.register_alias( "lottblocks:door_lebethron_lock_b",  "lord_wooden_stuff:door_lebethron_lock_b"  )
	core.register_alias( "lottblocks:door_lebethron_lock_c",  "lord_wooden_stuff:door_lebethron_lock_c"  )
	core.register_alias( "lottblocks:door_lebethron_lock_d",  "lord_wooden_stuff:door_lebethron_lock_d"  )
	core.register_alias( "lottblocks:door_mallorn",           "lord_wooden_stuff:door_mallorn"           )
	core.register_alias( "lottblocks:door_mallorn_a",         "lord_wooden_stuff:door_mallorn_a"         )
	core.register_alias( "lottblocks:door_mallorn_b",         "lord_wooden_stuff:door_mallorn_b"         )
	core.register_alias( "lottblocks:door_mallorn_c",         "lord_wooden_stuff:door_mallorn_c"         )
	core.register_alias( "lottblocks:door_mallorn_d",         "lord_wooden_stuff:door_mallorn_d"         )
	core.register_alias( "lottblocks:door_mallorn_lock",      "lord_wooden_stuff:door_mallorn_lock"      )
	core.register_alias( "lottblocks:door_mallorn_lock_a",    "lord_wooden_stuff:door_mallorn_lock_a"    )
	core.register_alias( "lottblocks:door_mallorn_lock_b",    "lord_wooden_stuff:door_mallorn_lock_b"    )
	core.register_alias( "lottblocks:door_mallorn_lock_c",    "lord_wooden_stuff:door_mallorn_lock_c"    )
	core.register_alias( "lottblocks:door_mallorn_lock_d",    "lord_wooden_stuff:door_mallorn_lock_d"    )
	core.register_alias( "lottblocks:door_pine",              "lord_wooden_stuff:door_pine"              )
	core.register_alias( "lottblocks:door_pine_a",            "lord_wooden_stuff:door_pine_a"            )
	core.register_alias( "lottblocks:door_pine_b",            "lord_wooden_stuff:door_pine_b"            )
	core.register_alias( "lottblocks:door_pine_c",            "lord_wooden_stuff:door_pine_c"            )
	core.register_alias( "lottblocks:door_pine_d",            "lord_wooden_stuff:door_pine_d"            )
	core.register_alias( "lottblocks:door_pine_lock",         "lord_wooden_stuff:door_pine_lock"         )
	core.register_alias( "lottblocks:door_pine_lock_a",       "lord_wooden_stuff:door_pine_lock_a"       )
	core.register_alias( "lottblocks:door_pine_lock_b",       "lord_wooden_stuff:door_pine_lock_b"       )
	core.register_alias( "lottblocks:door_pine_lock_c",       "lord_wooden_stuff:door_pine_lock_c"       )
	core.register_alias( "lottblocks:door_pine_lock_d",       "lord_wooden_stuff:door_pine_lock_d"       )
end

local function register_hatches_aliases()
	core.register_alias( "lottblocks:hatch_alder",           "lord_wooden_stuff:hatch_alder"           )
	core.register_alias( "lottblocks:hatch_alder_open",      "lord_wooden_stuff:hatch_alder_open"      )
	core.register_alias( "lottblocks:hatch_beech",           "lord_wooden_stuff:hatch_beech"           )
	core.register_alias( "lottblocks:hatch_beech_open",      "lord_wooden_stuff:hatch_beech_open"      )
	core.register_alias( "lottblocks:hatch_birch",           "lord_wooden_stuff:hatch_birch"           )
	core.register_alias( "lottblocks:hatch_birch_open",      "lord_wooden_stuff:hatch_birch_open"      )
	core.register_alias( "lottblocks:hatch_cherry",          "lord_wooden_stuff:hatch_cherry"          )
	core.register_alias( "lottblocks:hatch_cherry_open",     "lord_wooden_stuff:hatch_cherry_open"     )
	core.register_alias( "lottblocks:hatch_culumalda",       "lord_wooden_stuff:hatch_culumalda"       )
	core.register_alias( "lottblocks:hatch_culumalda_open",  "lord_wooden_stuff:hatch_culumalda_open"  )
	core.register_alias( "lottblocks:hatch_elm",             "lord_wooden_stuff:hatch_elm"             )
	core.register_alias( "lottblocks:hatch_elm_open",        "lord_wooden_stuff:hatch_elm_open"        )
	core.register_alias( "lottblocks:hatch_fir",             "lord_wooden_stuff:hatch_fir"             )
	core.register_alias( "lottblocks:hatch_fir_open",        "lord_wooden_stuff:hatch_fir_open"        )
	core.register_alias( "lottblocks:hatch_hardwood",        "lord_wooden_stuff:hatch_hardwood"        )
	core.register_alias( "lottblocks:hatch_hardwood_open",   "lord_wooden_stuff:hatch_hardwood_open"   )
	core.register_alias( "lottblocks:hatch_junglewood",      "lord_wooden_stuff:hatch_junglewood"      )
	core.register_alias( "lottblocks:hatch_junglewood_open", "lord_wooden_stuff:hatch_junglewood_open" )
	core.register_alias( "lottblocks:hatch_lebethron",       "lord_wooden_stuff:hatch_lebethron"       )
	core.register_alias( "lottblocks:hatch_lebethron_open",  "lord_wooden_stuff:hatch_lebethron_open"  )
	core.register_alias( "lottblocks:hatch_mallorn",         "lord_wooden_stuff:hatch_mallorn"         )
	core.register_alias( "lottblocks:hatch_mallorn_open",    "lord_wooden_stuff:hatch_mallorn_open"    )
	core.register_alias( "lottblocks:hatch_pine",            "lord_wooden_stuff:hatch_pine"            )
	core.register_alias( "lottblocks:hatch_pine_open",       "lord_wooden_stuff:hatch_pine_open"       )
	core.register_alias( "lottblocks:hatch_plum",            "lord_wooden_stuff:hatch_plum"            )
	core.register_alias( "lottblocks:hatch_plum_open",       "lord_wooden_stuff:hatch_plum_open"       )
end

local function register_fences_aliases()
	core.register_alias( "lottblocks:fence_alder",          "lord_wooden_stuff:fence_alder"          )
	core.register_alias( "lottblocks:fence_beech",          "lord_wooden_stuff:fence_beech"          )
	core.register_alias( "lottblocks:fence_birch",          "lord_wooden_stuff:fence_birch"          )
	core.register_alias( "lottblocks:fence_cherry",         "lord_wooden_stuff:fence_cherry"         )
	core.register_alias( "lottblocks:fence_culumalda",      "lord_wooden_stuff:fence_culumalda"      )
	core.register_alias( "lottblocks:fence_elm",            "lord_wooden_stuff:fence_elm"            )
	core.register_alias( "lottblocks:fence_fir",            "lord_wooden_stuff:fence_fir"            )
	core.register_alias( "lottblocks:fence_hardwood",       "lord_wooden_stuff:fence_hardwood"       )
	core.register_alias( "lottblocks:fence_lebethron",      "lord_wooden_stuff:fence_lebethron"      )
	core.register_alias( "lottblocks:fence_mallorn",        "lord_wooden_stuff:fence_mallorn"        )
	core.register_alias( "lottblocks:fence_pine",           "lord_wooden_stuff:fence_pine"           )
	core.register_alias( "lottblocks:fence_plum",           "lord_wooden_stuff:fence_plum"           )
	core.register_alias( "lottblocks:fence_rail_alder",     "lord_wooden_stuff:fence_rail_alder"     )
	core.register_alias( "lottblocks:fence_rail_beech",     "lord_wooden_stuff:fence_rail_beech"     )
	core.register_alias( "lottblocks:fence_rail_birch",     "lord_wooden_stuff:fence_rail_birch"     )
	core.register_alias( "lottblocks:fence_rail_cherry",    "lord_wooden_stuff:fence_rail_cherry"    )
	core.register_alias( "lottblocks:fence_rail_culumalda", "lord_wooden_stuff:fence_rail_culumalda" )
	core.register_alias( "lottblocks:fence_rail_elm",       "lord_wooden_stuff:fence_rail_elm"       )
	core.register_alias( "lottblocks:fence_rail_fir",       "lord_wooden_stuff:fence_rail_fir"       )
	core.register_alias( "lottblocks:fence_rail_hardwood",  "lord_wooden_stuff:fence_rail_hardwood"  )
	core.register_alias( "lottblocks:fence_rail_lebethron", "lord_wooden_stuff:fence_rail_lebethron" )
	core.register_alias( "lottblocks:fence_rail_mallorn",   "lord_wooden_stuff:fence_rail_mallorn"   )
	core.register_alias( "lottblocks:fence_rail_pine",      "lord_wooden_stuff:fence_rail_pine"      )
	core.register_alias( "lottblocks:fence_rail_plum",      "lord_wooden_stuff:fence_rail_plum"      )
end

local function register_sticks_aliases()
	core.register_alias( "lottblocks:stick_alder",      "lord_wooden_stuff:stick_alder"      )
	core.register_alias( "lottblocks:stick_beech",      "lord_wooden_stuff:stick_beech"      )
	core.register_alias( "lottblocks:stick_birch",      "lord_wooden_stuff:stick_birch"      )
	core.register_alias( "lottblocks:stick_cherry",     "lord_wooden_stuff:stick_cherry"     )
	core.register_alias( "lottblocks:stick_culumalda",  "lord_wooden_stuff:stick_culumalda"  )
	core.register_alias( "lottblocks:stick_elm",        "lord_wooden_stuff:stick_elm"        )
	core.register_alias( "lottblocks:stick_fir",        "lord_wooden_stuff:stick_fir"        )
	core.register_alias( "lottblocks:stick_hardwood",   "lord_wooden_stuff:stick_hardwood"   )
	core.register_alias( "lottblocks:stick_junglewood", "lord_wooden_stuff:stick_junglewood" )
	core.register_alias( "lottblocks:stick_lebethron",  "lord_wooden_stuff:stick_lebethron"  )
	core.register_alias( "lottblocks:stick_mallorn",    "lord_wooden_stuff:stick_mallorn"    )
	core.register_alias( "lottblocks:stick_pine",       "lord_wooden_stuff:stick_pine"       )
	core.register_alias( "lottblocks:stick_plum",       "lord_wooden_stuff:stick_plum"       )
end

local function register_ladders_aliases()
	core.register_alias( "lottblocks:ladder_alder",      "lord_wooden_stuff:ladder_alder"      )
	core.register_alias( "lottblocks:ladder_beech",      "lord_wooden_stuff:ladder_beech"      )
	core.register_alias( "lottblocks:ladder_birch",      "lord_wooden_stuff:ladder_birch"      )
	core.register_alias( "lottblocks:ladder_cherry",     "lord_wooden_stuff:ladder_cherry"     )
	core.register_alias( "lottblocks:ladder_culumalda",  "lord_wooden_stuff:ladder_culumalda"  )
	core.register_alias( "lottblocks:ladder_elm",        "lord_wooden_stuff:ladder_elm"        )
	core.register_alias( "lottblocks:ladder_fir",        "lord_wooden_stuff:ladder_fir"        )
	core.register_alias( "lottblocks:ladder_hardwood",   "lord_wooden_stuff:ladder_hardwood"   )
	core.register_alias( "lottblocks:ladder_junglewood", "lord_wooden_stuff:ladder_junglewood" )
	core.register_alias( "lottblocks:ladder_lebethron",  "lord_wooden_stuff:ladder_lebethron"  )
	core.register_alias( "lottblocks:ladder_mallorn",    "lord_wooden_stuff:ladder_mallorn"    )
	core.register_alias( "lottblocks:ladder_pine",       "lord_wooden_stuff:ladder_pine"       )
	core.register_alias( "lottblocks:ladder_plum",       "lord_wooden_stuff:ladder_plum"       )
end

local function register_stanchions_aliases()
	core.register_alias( "lottblocks:alder_stanchion",      "lord_wooden_stuff:stanchion_alder"      )
	core.register_alias( "lottblocks:beech_stanchion",      "lord_wooden_stuff:stanchion_beech"      )
	core.register_alias( "lottblocks:birch_stanchion",      "lord_wooden_stuff:stanchion_birch"      )
	core.register_alias( "lottblocks:cherry_stanchion",     "lord_wooden_stuff:stanchion_cherry"     )
	core.register_alias( "lottblocks:culumalda_stanchion",  "lord_wooden_stuff:stanchion_culumalda"  )
	core.register_alias( "lottblocks:elm_stanchion",        "lord_wooden_stuff:stanchion_elm"        )
	core.register_alias( "lottblocks:fir_stanchion",        "lord_wooden_stuff:stanchion_fir"        )
	core.register_alias( "lottblocks:hardwood_stanchion",   "lord_wooden_stuff:stanchion_hardwood"   )
	core.register_alias( "lottblocks:junglewood_stanchion", "lord_wooden_stuff:stanchion_junglewood" )
	core.register_alias( "lottblocks:lebethron_stanchion",  "lord_wooden_stuff:stanchion_lebethron"  )
	core.register_alias( "lottblocks:mallorn_stanchion",    "lord_wooden_stuff:stanchion_mallorn"    )
	core.register_alias( "lottblocks:pine_stanchion",       "lord_wooden_stuff:stanchion_pine"       )
	core.register_alias( "lottblocks:plum_stanchion",       "lord_wooden_stuff:stanchion_plum"       )
	core.register_alias( "lottblocks:wood_stanchion",       "lord_wooden_stuff:stanchion_wood"       )
end

local function register_tables_aliases()
	core.register_alias( "lottblocks:alder_table",      "lord_wooden_stuff:table_alder"      )
	core.register_alias( "lottblocks:beech_table",      "lord_wooden_stuff:table_beech"      )
	core.register_alias( "lottblocks:birch_table",      "lord_wooden_stuff:table_birch"      )
	core.register_alias( "lottblocks:cherry_table",     "lord_wooden_stuff:table_cherry"     )
	core.register_alias( "lottblocks:culumalda_table",  "lord_wooden_stuff:table_culumalda"  )
	core.register_alias( "lottblocks:elm_table",        "lord_wooden_stuff:table_elm"        )
	core.register_alias( "lottblocks:fir_table",        "lord_wooden_stuff:table_fir"        )
	core.register_alias( "lottblocks:hardwood_table",   "lord_wooden_stuff:table_hardwood"   )
	core.register_alias( "lottblocks:junglewood_table", "lord_wooden_stuff:table_junglewood" )
	core.register_alias( "lottblocks:lebethron_table",  "lord_wooden_stuff:table_lebethron"  )
	core.register_alias( "lottblocks:mallorn_table",    "lord_wooden_stuff:table_mallorn"    )
	core.register_alias( "lottblocks:pine_table",       "lord_wooden_stuff:table_pine"       )
	core.register_alias( "lottblocks:plum_table",       "lord_wooden_stuff:table_plum"       )
	core.register_alias( "lottblocks:wood_table",       "lord_wooden_stuff:table_wood"       )
end

local function register_chairs_aliases()
	core.register_alias( "lottblocks:alder_chair",      "lord_wooden_stuff:chair_alder"      )
	core.register_alias( "lottblocks:beech_chair",      "lord_wooden_stuff:chair_beech"      )
	core.register_alias( "lottblocks:birch_chair",      "lord_wooden_stuff:chair_birch"      )
	core.register_alias( "lottblocks:cherry_chair",     "lord_wooden_stuff:chair_cherry"     )
	core.register_alias( "lottblocks:culumalda_chair",  "lord_wooden_stuff:chair_culumalda"  )
	core.register_alias( "lottblocks:elm_chair",        "lord_wooden_stuff:chair_elm"        )
	core.register_alias( "lottblocks:fir_chair",        "lord_wooden_stuff:chair_fir"        )
	core.register_alias( "lottblocks:hardwood_chair",   "lord_wooden_stuff:chair_hardwood"   )
	core.register_alias( "lottblocks:junglewood_chair", "lord_wooden_stuff:chair_junglewood" )
	core.register_alias( "lottblocks:lebethron_chair",  "lord_wooden_stuff:chair_lebethron"  )
	core.register_alias( "lottblocks:mallorn_chair",    "lord_wooden_stuff:chair_mallorn"    )
	core.register_alias( "lottblocks:pine_chair",       "lord_wooden_stuff:chair_pine"       )
	core.register_alias( "lottblocks:plum_chair",       "lord_wooden_stuff:chair_plum"       )
	core.register_alias( "lottblocks:wood_chair",       "lord_wooden_stuff:chair_wood"       )
end


local function register_aliases()
	register_doors_aliases()
	register_hatches_aliases()
	register_fences_aliases()
	register_sticks_aliases()
	register_ladders_aliases()
	register_stanchions_aliases()
	register_tables_aliases()
	register_chairs_aliases()
end


return { register_aliases = register_aliases, }
