name: luacheck

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: apt
      run: sudo apt-get install -y luarocks
    - name: luacheck install
      run: luarocks install --local luacheck
    - name: luacheck run
      run: $HOME/.luarocks/bin/luacheck ./
