dofile(minetest.get_modpath("mountgen").."/ui.lua")
dofile(minetest.get_modpath("mountgen").."/algorithms/height_map.lua")
dofile(minetest.get_modpath("mountgen").."/algorithms/cone.lua")
dofile(minetest.get_modpath("mountgen").."/algorithms/diamond_square.lua")
dofile(minetest.get_modpath("mountgen").."/mountgen.lua")
dofile(minetest.get_modpath("mountgen").."/map.lua")
