
-- @tags: legacy

-- fruits.lua
core.register_alias("lottplants:plum",             "lord_trees:plum")
core.register_alias("lottplants:yavannamirefruit", "lord_trees:yavannamire_fruit")

-- leaves.lua
core.register_alias("lottplants:alderleaf",       "lord_trees:alder_leaf")
core.register_alias("lottplants:appleleaf",       "lord_trees:apple_leaf")
core.register_alias("lottplants:birchleaf",       "lord_trees:birch_leaf")
core.register_alias("lottplants:beechleaf",       "lord_trees:beech_leaf")
core.register_alias("lottplants:cherryleaf",      "lord_trees:cherry_leaf")
core.register_alias("lottplants:culumaldaleaf",   "lord_trees:culumalda_leaf")
core.register_alias("lottplants:yellowflowers",   "lord_trees:yellow_flowers")
core.register_alias("lottplants:elmleaf",         "lord_trees:elm_leaf")
core.register_alias("lottplants:firleaf",         "lord_trees:fir_leaf")
core.register_alias("lottplants:lebethronleaf",   "lord_trees:lebethron_leaf")
core.register_alias("lottplants:mallornleaf",     "lord_trees:mallorn_leaf")
core.register_alias("lottplants:pineleaf",        "lord_trees:pine_leaf")
core.register_alias("lottplants:plumleaf",        "lord_trees:plum_leaf")
core.register_alias("lottplants:rowanleaf",       "lord_trees:rowan_leaf")
core.register_alias("lottplants:rowanberry",      "lord_trees:rowan_berry")
core.register_alias("lottplants:whiteleaf",       "lord_trees:white_leaf")
core.register_alias("lottplants:yavannamireleaf", "lord_trees:yavannamire_leaf")
core.register_alias("lottplants:mirkleaf",        "lord_trees:mirk_leaf")
core.register_alias("lottmapgen:mirkleaves",      "lord_trees:mirk_leaf") -- extra old alias
core.register_alias("default:jungleleaves",       "lord_trees:mirk_leaf")

-- saplings.lua
core.register_alias("default:junglesapling",         "lord_trees:mirk_sapling")
core.register_alias("lottplants:aldersapling",       "lord_trees:alder_sapling")
core.register_alias("lottplants:applesapling",       "lord_trees:apple_sapling")
core.register_alias("lottplants:birchsapling",       "lord_trees:birch_sapling")
core.register_alias("lottplants:beechsapling",       "lord_trees:beech_sapling")
core.register_alias("lottplants:cherrysapling",      "lord_trees:cherry_sapling")
core.register_alias("lottplants:culumaldasapling",   "lord_trees:culumalda_sapling")
core.register_alias("lottplants:elmsapling",         "lord_trees:elm_sapling")
core.register_alias("lottplants:firsapling",         "lord_trees:fir_sapling")
core.register_alias("lottplants:lebethronsapling",   "lord_trees:lebethron_sapling")
core.register_alias("lottplants:mallornsapling",     "lord_trees:mallorn_sapling")
core.register_alias("lottplants:pinesapling",        "lord_trees:pine_sapling")
core.register_alias("lottplants:plumsapling",        "lord_trees:plum_sapling")
core.register_alias("lottplants:rowansapling",       "lord_trees:rowan_sapling")
core.register_alias("lottplants:whitesapling",       "lord_trees:white_sapling")
core.register_alias("lottplants:yavannamiresapling", "lord_trees:yavannamire_sapling")
core.register_alias("lottplants:mirksapling",        "lord_trees:mirk_sapling")

-- trunks.lua
core.register_alias("lottplants:aldertree",          "lord_trees:alder_tree")
core.register_alias("lottplants:beechtree",          "lord_trees:beech_tree")
core.register_alias("lottplants:birchtree",          "lord_trees:birch_tree")
core.register_alias("lottplants:cherrytree",         "lord_trees:cherry_tree")
core.register_alias("lottplants:culumaldatree",      "lord_trees:culumalda_tree")
core.register_alias("lottplants:elmtree",            "lord_trees:elm_tree")
core.register_alias("lottplants:firtree",            "lord_trees:fir_tree")
core.register_alias("lottplants:lebethrontree",      "lord_trees:lebethron_tree")
core.register_alias("lottplants:mallorntree",        "lord_trees:mallorn_tree")
core.register_alias("lottplants:mallorn_young_tree", "lord_trees:mallorn_young_tree")
core.register_alias("lottplants:pinetree",           "lord_trees:pine_tree")

core.register_alias("lottplants:aldertrunk",          "lord_trees:alder_trunk")
core.register_alias("lottplants:beechtrunk",          "lord_trees:beech_trunk")
core.register_alias("lottplants:birchtrunk",          "lord_trees:birch_trunk")
core.register_alias("lottplants:cherrytrunk",         "lord_trees:cherry_trunk")
core.register_alias("lottplants:culumaldatrunk",      "lord_trees:culumalda_trunk")
core.register_alias("lottplants:elmtrunk",            "lord_trees:elm_trunk")
core.register_alias("lottplants:firtrunk",            "lord_trees:fir_trunk")
core.register_alias("lottplants:lebethrontrunk",      "lord_trees:lebethron_trunk")
core.register_alias("lottplants:mallorntrunk",        "lord_trees:mallorn_trunk")
core.register_alias("lottplants:mallorn_young_trunk", "lord_trees:mallorn_young_trunk")
core.register_alias("lottplants:pinetrunk",           "lord_trees:pine_trunk")


-- DEFAULTS (Ghost blocks)
-- leaves.lua
core.register_alias("defaults:lottplants_alderleaf",       "defaults:lord_trees_alder_leaf")
core.register_alias("defaults:lottplants_appleleaf",       "defaults:lord_trees_apple_leaf")
core.register_alias("defaults:lottplants_birchleaf",       "defaults:lord_trees_birch_leaf")
core.register_alias("defaults:lottplants_beechleaf",       "defaults:lord_trees_beech_leaf")
core.register_alias("defaults:lottplants_cherryleaf",      "defaults:lord_trees_cherry_leaf")
core.register_alias("defaults:lottplants_culumaldaleaf",   "defaults:lord_trees_culumalda_leaf")
core.register_alias("defaults:lottplants_yellowflowers",   "defaults:lord_trees_yellow_flowers")
core.register_alias("defaults:lottplants_elmleaf",         "defaults:lord_trees_elm_leaf")
core.register_alias("defaults:lottplants_firleaf",         "defaults:lord_trees_fir_leaf")
core.register_alias("defaults:lottplants_lebethronleaf",   "defaults:lord_trees_lebethron_leaf")
core.register_alias("defaults:lottplants_mallornleaf",     "defaults:lord_trees_mallorn_leaf")
core.register_alias("defaults:lottplants_pineleaf",        "defaults:lord_trees_pine_leaf")
core.register_alias("defaults:lottplants_plumleaf",        "defaults:lord_trees_plum_leaf")
core.register_alias("defaults:lottplants_rowanleaf",       "defaults:lord_trees_rowan_leaf")
core.register_alias("defaults:lottplants_rowanberry",      "defaults:lord_trees_rowan_berry")
core.register_alias("defaults:lottplants_whiteleaf",       "defaults:lord_trees_white_leaf")
core.register_alias("defaults:lottplants_yavannamireleaf", "defaults:lord_trees_yavannamire_leaf")
core.register_alias("defaults:lottplants_mirkleaf",        "defaults:lord_trees_mirk_leaf")
core.register_alias("defaults:lottmapgen_mirkleaves",      "defaults:lord_trees_mirk_leaf") -- extra old alias
core.register_alias("defaults:default_jungleleaves",       "defaults:lord_trees_mirk_leaf")

-- trunks.lua
core.register_alias("defaults:lottplants_aldertree",          "defaults:lord_trees_alder_tree")
core.register_alias("defaults:lottplants_beechtree",          "defaults:lord_trees_beech_tree")
core.register_alias("defaults:lottplants_birchtree",          "defaults:lord_trees_birch_tree")
core.register_alias("defaults:lottplants_cherrytree",         "defaults:lord_trees_cherry_tree")
core.register_alias("defaults:lottplants_culumaldatree",      "defaults:lord_trees_culumalda_tree")
core.register_alias("defaults:lottplants_elmtree",            "defaults:lord_trees_elm_tree")
core.register_alias("defaults:lottplants_firtree",            "defaults:lord_trees_fir_tree")
core.register_alias("defaults:lottplants_lebethrontree",      "defaults:lord_trees_lebethron_tree")
core.register_alias("defaults:lottplants_mallorntree",        "defaults:lord_trees_mallorn_tree")
core.register_alias("defaults:lottplants_mallorn_young_tree", "defaults:lord_trees_mallorn_young_tree")
core.register_alias("defaults:lottplants_pinetree",           "defaults:lord_trees_pine_tree")

core.register_alias("defaults:lottplants_aldertrunk",          "defaults:lord_trees_alder_trunk")
core.register_alias("defaults:lottplants_beechtrunk",          "defaults:lord_trees_beech_trunk")
core.register_alias("defaults:lottplants_birchtrunk",          "defaults:lord_trees_birch_trunk")
core.register_alias("defaults:lottplants_cherrytrunk",         "defaults:lord_trees_cherry_trunk")
core.register_alias("defaults:lottplants_culumaldatrunk",      "defaults:lord_trees_culumalda_trunk")
core.register_alias("defaults:lottplants_elmtrunk",            "defaults:lord_trees_elm_trunk")
core.register_alias("defaults:lottplants_firtrunk",            "defaults:lord_trees_fir_trunk")
core.register_alias("defaults:lottplants_lebethrontrunk",      "defaults:lord_trees_lebethron_trunk")
core.register_alias("defaults:lottplants_mallorntrunk",        "defaults:lord_trees_mallorn_trunk")
core.register_alias("defaults:lottplants_mallorn_young_trunk", "defaults:lord_trees_mallorn_young_trunk")
core.register_alias("defaults:lottplants_pinetrunk",           "defaults:lord_trees_pine_trunk")


-- previous renaming
core.register_alias("lottplants:mallorntrunk_young", "lord_trees:mallorn_young_trunk")
core.register_alias("lottplants:mallorntree_young",  "lord_trees:mallorn_young_tree")
core.register_alias("defaults:lottplants_mallorntrunk_young", "defaults:lord_trees_mallorn_young_trunk")
core.register_alias("defaults:lottplants_mallorntree_young",  "defaults:lord_trees_mallorn_young_tree")
