## Выкладка на боевой сервер (game.lord-server.ru)

name: Deploy to Production Server
on:
  push:
    tags:
      - 20[0-9][0-9].[0-9][0-9]
      - 20[0-9][0-9].[0-9][0-9].p[0-9]


jobs:

  deploy-to-production:
    uses: ./.github/workflows/job.depoy.yml
    with:
      environment: production
      config_file: minetest.conf.prod
      branch:      master
      service:     lord-production
    secrets: inherit

  merge-to-dev:
    uses: ./.github/workflows/job.merge.yml
