
name: Deploy to Staging Server
on:
  push:
    branches:
      - test-deploy

jobs:

  deploy-to-staging:
    uses: ./.github/workflows/job.depoy.yml
    with:
      environment: staging
      config_file: minetest.conf.stage
      branch:      dev
      service:     lord-lord
    secrets: inherit
